version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/authorizer
hooks:
  BeforeInstall:
    - location: scripts/clean_build.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: scripts/reboot.sh
      timeout: 30
      runas: root
